// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUlElj3dNxJ_jsGSpT0MakDo_oP4yzeME',
    appId: '1:93651264775:web:2907fe5f2469db0deb11a2',
    messagingSenderId: '93651264775',
    projectId: 'dmit2504-fbstart',
    authDomain: 'dmit2504-fbstart.firebaseapp.com',
    storageBucket: 'dmit2504-fbstart.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4RxVP72ARk2DQslulNNq9qI3YS96ut74',
    appId: '1:93651264775:android:7abd45a8082e6f0feb11a2',
    messagingSenderId: '93651264775',
    projectId: 'dmit2504-fbstart',
    storageBucket: 'dmit2504-fbstart.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1y_fCCCHYMtvahtTWVtbN2geEt7HCxJI',
    appId: '1:93651264775:ios:c312adb9b74e2fd6eb11a2',
    messagingSenderId: '93651264775',
    projectId: 'dmit2504-fbstart',
    storageBucket: 'dmit2504-fbstart.firebasestorage.app',
    iosBundleId: 'com.example.harmonylink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1y_fCCCHYMtvahtTWVtbN2geEt7HCxJI',
    appId: '1:93651264775:ios:c312adb9b74e2fd6eb11a2',
    messagingSenderId: '93651264775',
    projectId: 'dmit2504-fbstart',
    storageBucket: 'dmit2504-fbstart.firebasestorage.app',
    iosBundleId: 'com.example.harmonylink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUlElj3dNxJ_jsGSpT0MakDo_oP4yzeME',
    appId: '1:93651264775:web:d9fb53eaca03efafeb11a2',
    messagingSenderId: '93651264775',
    projectId: 'dmit2504-fbstart',
    authDomain: 'dmit2504-fbstart.firebaseapp.com',
    storageBucket: 'dmit2504-fbstart.firebasestorage.app',
  );
}
